### ISSUE TITLE
error of open api request is not shown as the error message

### ISSUE THREAD

**Issue by minheibis** [c-3lab/dim#112]
https://github.com/c-3lab/dim/blob/c546fdc587cce0c70c7186d9742de9f2656d72ad/libs/openai_client.ts#L33-L36

この部分について、
エラーが発生すると、"Request failed with status code 404 Not Found"
のように表示されますが、これは ky のエラーメッセージを表示しており、open AI 側のレスポンスのエラーメッセージ（例えば以下を参照）が表示されていないようです。

コマンド例
```
curl -i https://api.openai.com/v1/completions -H \
    "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d '{
         "model": "gpt-3.5-turbo",
         "prompt": "generate the code that prints the following messange in python: this is a test",
         "max_tokens": 7,
         "temperature": 0
    }'
```
出力
```
HTTP/2 404 
date: Thu, 15 Jun 2023 12:13:02 GMT
content-type: application/json
content-length: 227
access-control-allow-origin: *
openai-organization: albert-inc-1
openai-processing-ms: 268
openai-version: 2020-10-01
strict-transport-security: max-age=15724800; includeSubDomains
x-ratelimit-limit-requests: 3500
x-ratelimit-limit-tokens: 90000
x-ratelimit-remaining-requests: 3499
x-ratelimit-remaining-tokens: 89992
x-ratelimit-reset-requests: 17ms
x-ratelimit-reset-tokens: 4ms
x-request-id: 9bdd4ddbcedcce031c323eb331076f87
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 7d7ab9887db0afdb-NRT
alt-svc: h3=":443"; ma=86400

{
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}
```

このメッセージの"message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?"を表示したいです。

**Comment by minheibis** [comment]
sindresorhus/ky: 🌳 Tiny & elegant JavaScript HTTP client based on the browser Fetch API - https://github.com/sindresorhus/ky#httperror
をみると、以下のようにすれば取得できそうな感じがします。

HTTPError
Exposed for instanceof checks. The error has a response property with the [Response object](https://developer.mozilla.org/en-US/docs/Web/API/Response), request property with the [Request object](https://developer.mozilla.org/en-US/docs/Web/API/Request), and options property with normalized options (either passed to ky when creating an instance with ky.create() or directly when performing the request).

If you need to read the actual response when an HTTPError has occurred, call the respective parser method on the response object. For example:

```
try {
	await ky('https://example.com').json();
} catch (error) {
	if (error.name === 'HTTPError') {
		const errorJson = await error.response.json();
	}
}
```

**Comment by ryo-ma** [comment]
@minheibis 提案ありがとうございます。もしPRできそうであればお待ち致しますがいかがですか？

**Comment by minheibis** [comment]
@ryo-ma こちらちょっとやってみます！遅くなって恐縮ですが、今週来週くらいに作業してみようと思います。

**Comment by ryo-ma** [comment]
ありがとうございます。いつでもお待ちしております。
